# Generated by Django 2.2.1 on 2019-05-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
