# Generated by Django 2.2.1 on 2019-05-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='desc',
            new_name='description',
        ),
    ]
