# Generated by Django 2.2.1 on 2019-05-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190513_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
