# Generated by Django 2.2.1 on 2019-05-15 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190515_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Schedule')),
            ],
        ),
    ]
