# Generated by Django 2.2.1 on 2019-05-14 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190513_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='Возрастной лимит'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=200, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Афиша'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.DateField(null=True, verbose_name='Премьера'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Назвние'),
        ),
    ]
