# Generated by Django 2.2.1 on 2019-05-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190514_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='desc',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
